language: ruby
sudo: required
services:
  - docker
rvm:
  - 2.5.0
env:
  - IMAGE=centos:7
  - IMAGE=debian:jessie
bundler_args: "--jobs=4"
cache: bundler
before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
script:
  - bundle exec itamae docker --node-yaml=recipes/node.yml recipes/install.rb --image=$IMAGE --tag itamae-plugin:latest
  - DOCKER_IMAGE=itamae-plugin:latest bundle exec rspec
